### ISSUE TITLE
unsupported/Eigen/CXX11/Tensor: No such file or directory

### ISSUE THREAD

**Issue by berli** [hemajun815/tfcc_image_classify#1]
make
g++ -std=c++11 ./src/dataset.cc ./src/image_classifier.cc ./src/main.cc -o tfcc_mnist.out -I/usr/local/include/tensorflow/ -L/usr/local/lib/tensorflow_cc/ -ltensorflow_framework -ltensorflow_cc -Wl,-rpath=/usr/local/lib/tensorflow_cc/
In file included from /usr/local/include/tensorflow/tensorflow/core/framework/tensor.h:19:0,
                 from /usr/local/include/tensorflow/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tensorflow/tensorflow/cc/ops/array_ops.h:8,
                 from /usr/local/include/tensorflow/tensorflow/cc/ops/standard_ops.h:19,
                 from ./src/image_classifier.h:1,
                 from ./src/image_classifier.cc:1:
/usr/local/include/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
compilation terminated.
In file included from /usr/local/include/tensorflow/tensorflow/core/framework/tensor.h:19:0,
                 from /usr/local/include/tensorflow/tensorflow/cc/framework/ops.h:21,
                 from /usr/local/include/tensorflow/tensorflow/cc/ops/array_ops.h:8,
                 from /usr/local/include/tensorflow/tensorflow/cc/ops/standard_ops.h:19,
                 from ./src/image_classifier.h:1,
                 from ./src/main.cc:2:
/usr/local/include/tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: fatal error: unsupported/Eigen/CXX11/Tensor: No such file or directory
compilation terminated.
makefile:9: recipe for target 'tfcc_mnist.out' failed
make: *** [tfcc_mnist.out] Error 1

**Comment by mag1c-h** [comment]
Hi, @berli . when you want to compile the tensorflow_cc code, you should first compile tensorflow source code into c++ library file. which steps as follow:
```
sudo apt install bazel
git clone --recursive https://github.com/tensorflow/tensorflow
./tensorflow/contrib/makefile/build_all_linux.sh
./configure
bazel build //tensorflow:libtensorflow_cc.so

sudo mkdir /usr/local/tensorflow
sudo mkdir /usr/local/tensorflow/include
sudo cp -r tensorflow/contrib/makefile/downloads/eigen/Eigen /usr/local/tensorflow/include/
sudo cp -r tensorflow/contrib/makefile/downloads/eigen/unsupported /usr/local/tensorflow/include/
sudo cp -r tensorflow/contrib/makefile/gen/protobuf/include/google /usr/local/tensorflow/include/
sudo cp tensorflow/contrib/makefile/downloads/nsync/public/* /usr/local/tensorflow/include/
sudo cp -r bazel-genfiles/tensorflow /usr/local/tensorflow/include/
sudo cp -r tensorflow/cc /usr/local/tensorflow/include/tensorflow
sudo cp -r tensorflow/core /usr/local/tensorflow/include/tensorflow
sudo mkdir /usr/local/tensorflow/include/third_party
sudo cp -r third_party/eigen3 /usr/local/tensorflow/include/third_party/
sudo mkdir /usr/local/tensorflow/lib
sudo cp bazel-bin/tensorflow/libtensorflow_*.so /usr/local/tensorflow/lib
```
A more detailed explanation, please see this **Chinese** tutorial: [compilling tensorflow source code into C++ library file](https://github.com/hemajun815/tutorial/blob/master/tensorflow/compilling-tensorflow-source-code-into-C++-library-file.md)

**Comment by robosina** [comment]
Hi, I still struggling with this issue
there is no `tensorflow/contrib/makefile/downloads/eigen/Eigen` directory in my bazel build or `tensorflow/contrib/makefile/downloads/eigen/unsupported` 

I think that the problem is raised in `./tensorflow/contrib/makefile/build_all_linux.sh` step, because I'm on windows, so do you know how I can solve this issue?
